# Generated by Django 4.1.1 on 2022-09-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_generateimage_data_getedgeandlebel_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bodyDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulderWidth', models.TextField()),
                ('chestWidth', models.TextField()),
                ('clothingLength', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lidardataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poseImg', models.TextField()),
                ('keypoints', models.TextField()),
            ],
        ),
    ]
